Optimized recipes and finished mmsagent init script.

diff --git a/mmsagent/templates/default/mmsagent.init.erb b/mmsagent/templates/default/mmsagent.init.erb
--- a/mmsagent/templates/default/mmsagent.init.erb
+++ b/mmsagent/templates/default/mmsagent.init.erb
@@ -32,7 +32,9 @@
 ### END INIT INFO
 
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-AGENT=<%= node[:mmsagent][:installdir] %>/agent.py
+INSTALLDIR=<%= node[:mmsagent][:installdir] %>
+AGENT=agent.py
+PYTHON=$(which python)
 
 # Default defaults. Can be overridden by the /etc/default/$NAME
 NAME=mmsagent
@@ -46,8 +48,8 @@ if [ -f /etc/default/$NAME ] ; then
 	. /etc/default/$NAME
 fi
 
-if test ! -f $AGENT; then
-    echo "Could not find $AGENT"
+if test ! -f $INSTALLDIR/$AGENT; then
+    echo "Could not find $INSTALLDIR/$AGENT"
     exit 0
 fi
 
@@ -87,15 +89,15 @@ running() {
     # No pidfile, probably no daemon present
     [ ! -f "$PIDFILE" ] && return 1
     pid=`cat $PIDFILE`
-    running_pid $pid $AGENT || return 1
+    running_pid $pid $PYTHON || return 1
     return 0
 }
 
 start_server() {
 # Start the process using the wrapper
             start-stop-daemon --background --start --quiet --pidfile $PIDFILE \
-                        --make-pidfile --chuid $DAEMONUSER \
-                        --exec $AGENT
+                        --make-pidfile --chuid $DAEMONUSER --chdir $INSTALLDIR \
+                        --exec $PYTHON -- $AGENT > $LOGFILE 2>&1
             errcode=$?
 	return $errcode
 }
@@ -105,7 +107,7 @@ stop_server() {
             start-stop-daemon --stop --quiet --pidfile $PIDFILE \
                         --retry 300 \
                         --user $DAEMONUSER \
-                        --exec $AGENT
+                        --exec $PYTHON
             errcode=$?
 	return $errcode
 }
